### ISSUE TITLE
No `Create a pipeline server` to click on

### ISSUE THREAD

**Issue by adelton** [RedHatQuickCourses/rhods-pipelines#18]
Page https://redhatquickcourses.github.io/rhods-pipelines/rhods-pipelines/1.33/chapter1/dspa.html says:

> 4. Click on the `Create a pipeline server` in the `Pipelines` section of the Data Science Project view

With OpenShift AI 2.8.0 operator, there is no `Create a pipeline server` there. Instead there is a `Configure pipeline server` button there.

![Screenshot_2024-04-04_10-24-32](https://github.com/RedHatQuickCourses/rhods-pipelines/assets/2536912/8c171801-4987-47eb-bbd2-2c320e2e7e2c)

**Comment by adelton** [comment]
The next step 5 is also different than described, there is no `Existing data connection` in the form. Instead the data connections are hidden under that tiny key icon:

![Screenshot_2024-04-04_10-26-12](https://github.com/RedHatQuickCourses/rhods-pipelines/assets/2536912/058bca32-a414-41ec-b682-88abc25978c9)

**Comment by rsriniva** [comment]
fixed in PR #25
