### ISSUE TITLE
`Import new image` now calls Repository Image location

### ISSUE THREAD

**Issue by adelton** [RedHatQuickCourses/rhods-pipelines#20]
Page https://redhatquickcourses.github.io/rhods-pipelines/rhods-pipelines/1.33/chapter1/elyra-pipelines.html says:

> Select `Import new image` and enter the following details:
> Repository: quay.io/mmurakam/workbenches:fraud-detection-v1.0.1

With OpenShift AI 2.8.0 the field is now called Image location.
![Screenshot_2024-04-04_12-56-39](https://github.com/RedHatQuickCourses/rhods-pipelines/assets/2536912/2ce47788-2a86-453c-929f-211aa0593b4c)

**Comment by rsriniva** [comment]
fixed in PR #25
