### ISSUE TITLE
PIPELINES_SSL_SA_CERTS typo

### ISSUE THREAD

**Issue by viniciusfcf** [RedHatQuickCourses/rhods-pipelines#24]
Change PIPELINES_SSL_SA_CERTS by PIPELINES_SSL_CA_CERTS in the page: https://redhatquickcourses.github.io/rhods-pipelines/rhods-pipelines/1.33/chapter1/elyra-pipelines.html

**Comment by rsriniva** [comment]
fixed in PR #25
